use phf::phf_map;
use std::collections::HashMap;

static EXTENSION_MAP: phf::Map<&'static str, &'static str> = phf_map! {
    "rs" => "Rust",
    "py" => "Python",
    "js" => "JavaScript",
    "ts" => "TypeScript",
    "jsx" => "JavaScript",
    "tsx" => "TypeScript",
    "go" => "Go",
    "c" => "C",
    "cpp" => "C++",
    "h" => "C/C++ Header",
    "hpp" => "C++ Header",
    "cs" => "C#",
    "java" => "Java",
    "php" => "PHP",
    "rb" => "Ruby",
    "sql" => "SQL",
    "html" => "HTML",
    "css" => "CSS",
    "json" => "JSON",
    "yaml" => "YAML",
    "yml" => "YAML",
    "xml" => "XML",
    "sh" => "Shell",
    "bash" => "Shell",
    "md" => "Markdown",
    "ex" => "Elixir",
    "exs" => "Elixir",
    "heex" => "Elixir (HEEx)",
    "erl" => "Erlang",
    "swift" => "Swift",
    "kt" => "Kotlin",
    "toml" => "TOML",
    "dockerfile" => "Dockerfile",
};

#[derive(Default, Clone, Debug)]
pub struct LanguageStats {
    pub occurrences: u32,
    pub bytes: usize,
}

#[derive(Default, Clone, Debug)]
pub struct LanguageAnalyzer {
    pub stats: HashMap<String, LanguageStats>,
}

impl LanguageAnalyzer {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn record_file_edit(&mut self, file_path: &str, byte_count: usize) {
        if let Some(ext) = Self::extract_extension(file_path) {
            let ext_lower = ext.to_lowercase();
            if let Some(lang) = EXTENSION_MAP.get(ext_lower.as_str()) {
                let entry = self.stats.entry(lang.to_string()).or_default();
                entry.occurrences += 1;
                entry.bytes += byte_count;
            } else {
                // Ignore unknown extensions completely
            }
        } else if file_path.to_lowercase().ends_with("dockerfile") {
            let entry = self.stats.entry("Dockerfile".to_string()).or_default();
            entry.occurrences += 1;
            entry.bytes += byte_count;
        }
    }

    fn extract_extension(path: &str) -> Option<&str> {
        let path = path.trim();
        if path.is_empty() {
            return None;
        }

        let last_slash = path.rfind('/').unwrap_or(0);
        let file_name = &path[last_slash..];

        if let Some(dot_idx) = file_name.rfind('.') {
            if dot_idx > 0 && dot_idx < file_name.len() - 1 {
                return Some(&file_name[dot_idx + 1..]);
            }
        }
        None
    }

    pub fn merge(&mut self, other: &LanguageAnalyzer) {
        for (lang, stats) in &other.stats {
            let entry = self.stats.entry(lang.clone()).or_insert(LanguageStats {
                occurrences: 0,
                bytes: 0,
            });
            entry.occurrences += stats.occurrences;
            entry.bytes += stats.bytes;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_file_edit() {
        let mut analyzer = LanguageAnalyzer::new();

        analyzer.record_file_edit("src/main.rs", 100);
        analyzer.record_file_edit("scripts/build.sh", 50);
        analyzer.record_file_edit("Dockerfile", 200);
        analyzer.record_file_edit("Makefile", 500); // Should be ignored
        analyzer.record_file_edit("unknown.txt", 10); // Should be ignored

        assert_eq!(analyzer.stats.get("Rust").map(|s| s.occurrences), Some(1));
        assert_eq!(analyzer.stats.get("Rust").map(|s| s.bytes), Some(100));
        assert_eq!(analyzer.stats.get("Shell").map(|s| s.occurrences), Some(1));
        assert_eq!(
            analyzer.stats.get("Dockerfile").map(|s| s.occurrences),
            Some(1)
        );
        assert!(!analyzer.stats.contains_key("Unknown"));
        assert!(!analyzer.stats.contains_key("Makefile"));
    }

    #[test]
    fn test_complex_and_markdown_paths() {
        let mut analyzer = LanguageAnalyzer::new();

        // 1. Realistic Markdown files
        analyzer.record_file_edit("README.md", 250);
        analyzer.record_file_edit("docs/api_implementation_plan.md", 1500);

        // 2. Case variations (.MD, .RS, .PY)
        analyzer.record_file_edit("UPPERCASE_TEST.MD", 400);
        analyzer.record_file_edit("src/lib.RS", 800);
        analyzer.record_file_edit("scripts/analyzer.Py", 300);

        // 3. Multi-dot extension patterns
        analyzer.record_file_edit("frontend/src/components/button.spec.tsx", 1200);

        // 4. Windows-style paths (sometimes generated by Windows tools)
        analyzer.record_file_edit("src\\utils\\helper.ts", 500);

        // Assertions for Markdown
        let md = analyzer
            .stats
            .get("Markdown")
            .expect("Markdown should be tracked");
        assert_eq!(md.occurrences, 3); // README.md + api_implementation_plan.md + UPPERCASE_TEST.MD
        assert_eq!(md.bytes, 250 + 1500 + 400);

        // Assertions for case-insensitive Rust/Python
        let rust = analyzer.stats.get("Rust").expect("Rust should be tracked");
        assert_eq!(rust.occurrences, 1);
        assert_eq!(rust.bytes, 800);

        let py = analyzer
            .stats
            .get("Python")
            .expect("Python should be tracked");
        assert_eq!(py.occurrences, 1);
        assert_eq!(py.bytes, 300);

        // Assertions for TypeScript (.tsx and .ts)
        let ts_stats = analyzer
            .stats
            .get("TypeScript")
            .expect("TypeScript should be tracked");
        assert_eq!(ts_stats.occurrences, 2); // button.spec.tsx + helper.ts
        assert_eq!(ts_stats.bytes, 1200 + 500);
    }
}
